import { describe, expect, test } from "vitest";
import {
  computeInvoiceTotals,
  formatMoney,
  formatRate,
  parseMoneyToCents,
  type InvoiceLine,
} from "./invoiceMath";

/**
 * The reference invoice (TSWS-082626, dual swing gate) that Eric bills today.
 * Every number here is copied from the PDF he generated by hand; the engine
 * must reproduce it exactly or it is not usable for real billing.
 *
 * His combined "labor + fuel" line is split into two rows (Option A): 25 hrs at
 * $175 plus a $44.08 fuel lot. That is the only structural change.
 */
const REFERENCE_LINES: InvoiceLine[] = [
  {
    qty: 1,
    unit: "ea",
    description:
      "LiftMaster LA400UL, dual-swing operator with solar panel and battery kit",
    rateCents: 299900,
    taxable: true,
  },
  {
    qty: 25,
    unit: "hr",
    description: "Fabrication, installation and mobilization labor",
    rateCents: 17500,
    taxable: true,
  },
  {
    qty: 1,
    unit: "lot",
    description: "Fuel — mobilization surcharge",
    rateCents: 4408,
    taxable: true,
  },
  {
    qty: 1,
    unit: "ea",
    description: "Steel tubing, metal and fabrication consumables",
    rateCents: 112460,
    taxable: true,
  },
  {
    qty: 1,
    unit: "ea",
    description: "Paint and finishing supplies",
    rateCents: 15000,
    taxable: true,
  },
  {
    qty: 1,
    unit: "ea",
    description: "Concrete",
    rateCents: 5000,
    taxable: true,
  },
  {
    qty: 1,
    unit: "ea",
    description: "Plasma-cutting consumables",
    rateCents: 5000,
    taxable: true,
  },
];

describe("computeInvoiceTotals — the reference invoice", () => {
  test("reproduces TSWS-082626 to the cent", () => {
    const totals = computeInvoiceTotals({
      lines: REFERENCE_LINES,
      discountCents: 0,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.subtotalCents).toBe(879268); // $8,792.68
    expect(totals.taxCents).toBe(72540); // $725.40
    expect(totals.balanceCents).toBe(951808); // $9,518.08
  });

  test("each line amount is qty times rate", () => {
    const totals = computeInvoiceTotals({
      lines: REFERENCE_LINES,
      discountCents: 0,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    // The labor line is the one that is not simply the rate: 25 x $175.
    expect(totals.lineAmountsCents[1]).toBe(437500);
    expect(totals.lineAmountsCents[2]).toBe(4408);
    expect(totals.lineAmountsCents).toHaveLength(REFERENCE_LINES.length);
  });
});

describe("computeInvoiceTotals — tax", () => {
  test("taxes only the lines flagged taxable", () => {
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 10,
          unit: "hr",
          description: "Labor",
          rateCents: 10000,
          taxable: false,
        },
        {
          qty: 1,
          unit: "ea",
          description: "Steel",
          rateCents: 50000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.subtotalCents).toBe(150000);
    expect(totals.taxableSubtotalCents).toBe(50000);
    // Only the $500 of steel is taxed: 50000 * 0.0825 = 4125.
    expect(totals.taxCents).toBe(4125);
    expect(totals.balanceCents).toBe(154125);
  });

  test("a zero tax rate produces no tax", () => {
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Gate",
          rateCents: 100000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 0,
      paymentsCents: 0,
    });

    expect(totals.taxCents).toBe(0);
    expect(totals.balanceCents).toBe(100000);
  });

  test("rounds tax half-up to the nearest cent", () => {
    // 1000 cents * 8.25% = 82.5 cents exactly -> 83, never 82.
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Odd",
          rateCents: 1000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.taxCents).toBe(83);
  });
});

describe("computeInvoiceTotals — discount and payments", () => {
  test("a discount reduces the taxable base, not just the total", () => {
    // $1,000 of taxable work, $100 off. Tax must be on $900, not $1,000.
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Work",
          rateCents: 100000,
          taxable: true,
        },
      ],
      discountCents: 10000,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.taxableSubtotalCents).toBe(90000);
    expect(totals.taxCents).toBe(7425);
    expect(totals.balanceCents).toBe(97425);
  });

  test("payments reduce the balance due but never the tax", () => {
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Work",
          rateCents: 100000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 825,
      paymentsCents: 50000,
    });

    expect(totals.taxCents).toBe(8250);
    expect(totals.totalCents).toBe(108250);
    expect(totals.balanceCents).toBe(58250);
  });

  test("an overpayment yields a negative balance rather than clamping to zero", () => {
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Work",
          rateCents: 10000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 0,
      paymentsCents: 15000,
    });

    // A credit is real information; silently clamping would hide it from Eric.
    expect(totals.balanceCents).toBe(-5000);
  });

  test("a discount larger than the subtotal cannot drive the taxable base below zero", () => {
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Work",
          rateCents: 10000,
          taxable: true,
        },
      ],
      discountCents: 25000,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.taxableSubtotalCents).toBe(0);
    expect(totals.taxCents).toBe(0);
  });

  test("splits a discount across taxable and non-taxable work proportionally", () => {
    // $600 taxable + $400 exempt = $1,000. A $100 discount removes $60 from
    // the taxable base, not the whole $100 -- otherwise tax is understated.
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1,
          unit: "ea",
          description: "Materials",
          rateCents: 60000,
          taxable: true,
        },
        {
          qty: 1,
          unit: "hr",
          description: "Exempt labor",
          rateCents: 40000,
          taxable: false,
        },
      ],
      discountCents: 10000,
      taxRateBasisPoints: 825,
      paymentsCents: 0,
    });

    expect(totals.taxableSubtotalCents).toBe(54000);
    expect(totals.taxCents).toBe(4455);
  });
});

describe("computeInvoiceTotals — rejects nonsense", () => {
  test("throws on a negative quantity", () => {
    expect(() =>
      computeInvoiceTotals({
        lines: [
          {
            qty: -1,
            unit: "ea",
            description: "Bad",
            rateCents: 1000,
            taxable: true,
          },
        ],
        discountCents: 0,
        taxRateBasisPoints: 825,
        paymentsCents: 0,
      }),
    ).toThrow(/quantity/i);
  });

  test("throws on a non-integer cent amount", () => {
    expect(() =>
      computeInvoiceTotals({
        lines: [
          {
            qty: 1,
            unit: "ea",
            description: "Bad",
            rateCents: 10.5,
            taxable: true,
          },
        ],
        discountCents: 0,
        taxRateBasisPoints: 825,
        paymentsCents: 0,
      }),
    ).toThrow(/whole cents/i);
  });

  test("throws on a negative tax rate", () => {
    expect(() =>
      computeInvoiceTotals({
        lines: [
          {
            qty: 1,
            unit: "ea",
            description: "Work",
            rateCents: 1000,
            taxable: true,
          },
        ],
        discountCents: 0,
        taxRateBasisPoints: -5,
        paymentsCents: 0,
      }),
    ).toThrow(/tax rate/i);
  });

  test("allows a fractional quantity for part-hours", () => {
    // 1.5 hours at $175 is a real thing Eric bills.
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 1.5,
          unit: "hr",
          description: "Labor",
          rateCents: 17500,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 0,
      paymentsCents: 0,
    });

    expect(totals.subtotalCents).toBe(26250);
  });

  test("rounds a line amount that lands on a fraction of a cent", () => {
    // 0.333 hr * $100.00 = 3330 cents exactly; 0.3333 * 10000 = 3333 cents.
    const totals = computeInvoiceTotals({
      lines: [
        {
          qty: 0.3333,
          unit: "hr",
          description: "Labor",
          rateCents: 10000,
          taxable: true,
        },
      ],
      discountCents: 0,
      taxRateBasisPoints: 0,
      paymentsCents: 0,
    });

    expect(Number.isInteger(totals.subtotalCents)).toBe(true);
    expect(totals.subtotalCents).toBe(3333);
  });
});

describe("formatMoney", () => {
  test("renders cents as US currency with a thousands separator", () => {
    expect(formatMoney(951808)).toBe("$9,518.08");
    expect(formatMoney(0)).toBe("$0.00");
    expect(formatMoney(5000)).toBe("$50.00");
  });

  test("renders a credit balance with a leading minus", () => {
    expect(formatMoney(-5000)).toBe("-$50.00");
  });
});

describe("formatRate", () => {
  test("appends the unit only for hourly lines, matching the paper invoice", () => {
    expect(formatRate(17500, "hr")).toBe("$175.00/hr");
    expect(formatRate(299900, "ea")).toBe("$2,999.00");
    expect(formatRate(4408, "lot")).toBe("$44.08");
  });

  test("labels measured units so a rate is never ambiguous", () => {
    expect(formatRate(1250, "ft")).toBe("$12.50/ft");
    expect(formatRate(275, "lb")).toBe("$2.75/lb");
  });
});

describe("parseMoneyToCents", () => {
  test("accepts what a person actually types into a phone", () => {
    expect(parseMoneyToCents("175")).toBe(17500);
    expect(parseMoneyToCents("175.00")).toBe(17500);
    expect(parseMoneyToCents("$1,124.60")).toBe(112460);
    expect(parseMoneyToCents("  44.08 ")).toBe(4408);
  });

  test("rounds a third decimal rather than truncating it", () => {
    expect(parseMoneyToCents("10.005")).toBe(1001);
  });

  test("returns null for junk so the caller can show an error", () => {
    expect(parseMoneyToCents("")).toBeNull();
    expect(parseMoneyToCents("abc")).toBeNull();
    expect(parseMoneyToCents("1.2.3")).toBeNull();
  });
});
